apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultigestapp:1.0.0:5
spec:
  replicas: 3
  selector:
    matchLabels:
      run: cultigestapp:1.0.0:5
  template:
    metadata:
      labels:
        run: cultigestapp:1.0.0:5
    spec:
      containers:
      - name: cultigestapp:1.0.0:5
        image: devopseasy/cultigestapp:1.0.0:5
        ports:
          - containerPort: 8080
        imagePullPolicy: IfNotPresent
