apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultigestapp:culti_12
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cultigestapp:culti_12
  template:
    metadata:
      labels:
        run: cultigestapp:culti_12
    spec:
      containers:
      - name: cultigestapp:culti_12
        image: devopseasy/cultigestapp:culti_12
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent
