apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultigestapp:1.0.0-7
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cultigestapp:1.0.0-7
  template:
    metadata:
      labels:
        run: cultigestapp:1.0.0-7
    spec:
      containers:
      - name: cultigestapp:1.0.0-7
        image: devopseasy/cultigestapp:1.0.0-7
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent
