apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultigestapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: cultigestapp
  template:
    metadata:
      labels:
        run: cultigestapp
    spec:
      containers:
      - name: cultigestapp
        image: devopseasy/cultigestapp:1.0.0-3
        ports:
          - containerPort: 8080
        imagePullPolicy: IfNotPresent
