apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultigestapp:1-11
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cultigestapp:1-11
  template:
    metadata:
      labels:
        run: cultigestapp:1-11
    spec:
      containers:
      - name: cultigestapp:1-11
        image: devopseasy/cultigestapp:1-11
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent
