apiVersion: apps/v1
kind: Deployment
metadata:
  name: cultigestapp:1.0.0-9
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cultigestapp
  template:
    metadata:
      labels:
        run: cultigestapp
    spec:
      containers:
      - name: cultigestapp:1.0.0-9
        image: devopseasy/cultigestapp:1.0.0-9
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent
