apiVersion: v1
kind: Service
metadata:
  name: cultigestapp
  labels:
    run: cultigestapp:1.0.0-10
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: cultigestapp:1.0.0-10
