apiVersion: v1
kind: Service
metadata:
  name: cultigestapp
  labels:
    run: cultigestapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: cultigestapp
